name: Publish Modules

on:
  workflow_dispatch:
    inputs:
      target_project:
        description: "Which project do you want to publish?"
        required: true
        type: choice
        options:
          - Implementation
          - API
          - Standard Library
          - Spotify Library

jobs:
  publish-a:
    if: ${{ github.event.inputs.target_project == 'Implementation' }}
    runs-on: ubuntu-latest
    # Concurrency key ensures that only one job in this group can run at a time
    concurrency:
      group: "gradle-publish"
      cancel-in-progress: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Publish Qilletni Implementation
        run: ./gradlew :publish
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-b:
    if: ${{ github.event.inputs.target_project == 'API' }}
    runs-on: ubuntu-latest
    concurrency:
      group: "gradle-publish"
      cancel-in-progress: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Publish Qilletni API
        run: ./gradlew :qilletni-api:publish
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-c:
    if: ${{ github.event.inputs.target_project == 'Standard Library' }}
    runs-on: ubuntu-latest
    concurrency:
      group: "gradle-publish"
      cancel-in-progress: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Publish Standard Library
        run: ./gradlew :qilletni-lib-std:publish
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-d:
    if: ${{ github.event.inputs.target_project == 'Spotify Library' }}
    runs-on: ubuntu-latest
    concurrency:
      group: "gradle-publish"
      cancel-in-progress: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Publish Spotify Library
        run: ./gradlew :qilletni-spotify:publish
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
